# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib annsearchR, .registration = TRUE
NULL

#' Describe an index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Reads the algorithm, precision and shape off an index pointer.
#'
#' @param ptr External pointer to an index.
#'
#' @returns A list with:
#' \itemize{
#'   \item algo - Algorithm name.
#'   \item precision - `"float"` or `"double"`.
#'   \item n - Number of indexed samples.
#'   \item dim - Number of features.
#' }
#'
#' @keywords internal
rs_ann_info <- function(ptr) .Call(wrap__rs_ann_info, ptr)

#' Save an index to a directory
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Writes `index.bin` into `dir`. Use the `$save()` method instead.
#'
#' @param ptr External pointer to an index.
#' @param dir String. Target directory, created if missing.
#'
#' @returns Invisible `NULL`.
#'
#' @keywords internal
rs_ann_save <- function(ptr, dir) .Call(wrap__rs_ann_save, ptr, dir)

#' Load an index from a directory
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Reads a bundle written by [rs_ann_save()]. Use [load_ann_index()] instead.
#'
#' @param dir String. Directory holding `index.bin`.
#' @param algo String. Algorithm that wrote the bundle.
#'
#' @returns External pointer to the index.
#'
#' @keywords internal
rs_ann_load <- function(dir, algo) .Call(wrap__rs_ann_load, dir, algo)

#' Set the number of threads used for builds and queries
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Installs a dedicated Rayon pool. Use [ann_set_threads()] instead.
#'
#' @param n Integer. Thread count. `0L` returns to Rayon's global pool, which
#' honours `RAYON_NUM_THREADS`.
#'
#' @returns Invisible `NULL`.
#'
#' @keywords internal
rs_set_threads <- function(n) .Call(wrap__rs_set_threads, n)

#' Number of threads used for builds and queries
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use [ann_get_threads()] instead.
#'
#' @returns Integer. The configured pool's size, or Rayon's global pool size.
#'
#' @keywords internal
rs_get_threads <- function() .Call(wrap__rs_get_threads)

#' Recall of an approximate kNN result against ground truth
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use [knn_recall()] instead.
#'
#' @param truth Integer matrix. Queries x k true neighbour indices.
#' @param approx Integer matrix. Queries x k approximate neighbour indices,
#' same shape as `truth`.
#'
#' @returns Numeric. Mean over queries of |truth ∩ approx| / k. `NA` entries in
#' `approx` never count as hits.
#'
#' @keywords internal
rs_knn_recall <- function(truth, approx) .Call(wrap__rs_knn_recall, truth, approx)

#' Generate clustered synthetic data
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Gaussian clusters with random centres and per-cluster spread, the same
#' generator the crate's own benchmarks use. Use
#' [generate_clustered_data()] instead.
#'
#' @param n Integer. Number of samples.
#' @param dim Integer. Number of features.
#' @param n_clusters Integer. Number of clusters.
#' @param seed Integer. Random seed.
#'
#' @returns A list with `data` (n x dim numeric matrix) and `labels` (1-based
#' integer cluster labels).
#'
#' @keywords internal
rs_data_clustered <- function(n, dim, n_clusters, seed) .Call(wrap__rs_data_clustered, n, dim, n_clusters, seed)

#' Build an exhaustive index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use [ExhaustiveIndex] instead.
#'
#' @param data Numeric matrix. Samples x features.
#' @param metric String. One of `c("euclidean", "cosine", "manhattan")`.
#' @param precision String. `"float"` or `"double"`.
#'
#' @returns External pointer to the index.
#'
#' @keywords internal
rs_exhaustive_build <- function(data, metric, precision) .Call(wrap__rs_exhaustive_build, data, metric, precision)

#' Query an exhaustive index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use the `$predict()` method instead.
#'
#' @param ptr External pointer to the index.
#' @param data Numeric matrix. Queries x features.
#' @param k Integer. Number of neighbours.
#' @param sqrt Boolean. Square root the distances (true Euclidean).
#' @param return_dist Boolean. Return the distances.
#' @param verbose Boolean. Print progress.
#'
#' @returns A list with `idx` (1-based integer matrix) and `dist` (double
#' matrix or `NULL`).
#'
#' @keywords internal
rs_exhaustive_query <- function(ptr, data, k, sqrt, return_dist, verbose) .Call(wrap__rs_exhaustive_query, ptr, data, k, sqrt, return_dist, verbose)

#' Self-query an exhaustive index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use the `$query_self()` method instead.
#'
#' @param ptr External pointer to the index.
#' @param k Integer. Number of neighbours, including the point itself.
#' @param sqrt Boolean. Square root the distances (true Euclidean).
#' @param return_dist Boolean. Return the distances.
#' @param verbose Boolean. Print progress.
#'
#' @returns A list with `idx` (1-based integer matrix) and `dist` (double
#' matrix or `NULL`).
#'
#' @keywords internal
rs_exhaustive_self <- function(ptr, k, sqrt, return_dist, verbose) .Call(wrap__rs_exhaustive_self, ptr, k, sqrt, return_dist, verbose)

#' Build an Annoy index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use [AnnoyIndex] instead.
#'
#' @param data Numeric matrix. Samples x features.
#' @param metric String. One of `c("euclidean", "cosine")`.
#' @param n_trees Integer. Number of trees.
#' @param seed Integer. Random seed.
#' @param precision String. `"float"` or `"double"`.
#'
#' @returns External pointer to the index.
#'
#' @keywords internal
rs_annoy_build <- function(data, metric, n_trees, seed, precision) .Call(wrap__rs_annoy_build, data, metric, n_trees, seed, precision)

#' Query an Annoy index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use the `$predict()` method instead.
#'
#' @param ptr External pointer to the index.
#' @param data Numeric matrix. Queries x features.
#' @param k Integer. Number of neighbours.
#' @param search_budget Integer or `NULL`. Candidates to inspect per query.
#' `NULL` lets the crate pick.
#' @param sqrt Boolean. Square root the distances (true Euclidean).
#' @param return_dist Boolean. Return the distances.
#' @param verbose Boolean. Print progress.
#'
#' @returns A list with `idx` (1-based integer matrix) and `dist` (double
#' matrix or `NULL`).
#'
#' @keywords internal
rs_annoy_query <- function(ptr, data, k, search_budget, sqrt, return_dist, verbose) .Call(wrap__rs_annoy_query, ptr, data, k, search_budget, sqrt, return_dist, verbose)

#' Self-query an Annoy index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use the `$query_self()` method instead.
#'
#' @param ptr External pointer to the index.
#' @param k Integer. Number of neighbours, including the point itself.
#' @param search_budget Integer or `NULL`. Candidates to inspect per query.
#' @param sqrt Boolean. Square root the distances (true Euclidean).
#' @param return_dist Boolean. Return the distances.
#' @param verbose Boolean. Print progress.
#'
#' @returns A list with `idx` (1-based integer matrix) and `dist` (double
#' matrix or `NULL`).
#'
#' @keywords internal
rs_annoy_self <- function(ptr, k, search_budget, sqrt, return_dist, verbose) .Call(wrap__rs_annoy_self, ptr, k, search_budget, sqrt, return_dist, verbose)

#' Build an HNSW index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use [HnswIndex] instead.
#'
#' @param data Numeric matrix. Samples x features.
#' @param metric String. One of `c("euclidean", "cosine", "manhattan")`.
#' @param m Integer. Edges per node on the upper layers.
#' @param ef_construction Integer. Candidate list width during the build.
#' @param seed Integer. Random seed.
#' @param precision String. `"float"` or `"double"`.
#' @param verbose Boolean. Print progress.
#'
#' @returns External pointer to the index.
#'
#' @keywords internal
rs_hnsw_build <- function(data, metric, m, ef_construction, seed, precision, verbose) .Call(wrap__rs_hnsw_build, data, metric, m, ef_construction, seed, precision, verbose)

#' Query an HNSW index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use the `$predict()` method instead.
#'
#' @param ptr External pointer to the index.
#' @param data Numeric matrix. Queries x features.
#' @param k Integer. Number of neighbours.
#' @param ef_search Integer. Beam width at query time.
#' @param sqrt Boolean. Square root the distances (true Euclidean).
#' @param return_dist Boolean. Return the distances.
#' @param verbose Boolean. Print progress.
#'
#' @returns A list with `idx` (1-based integer matrix) and `dist` (double
#' matrix or `NULL`).
#'
#' @keywords internal
rs_hnsw_query <- function(ptr, data, k, ef_search, sqrt, return_dist, verbose) .Call(wrap__rs_hnsw_query, ptr, data, k, ef_search, sqrt, return_dist, verbose)

#' Self-query an HNSW index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Use the `$query_self()` method instead.
#'
#' @param ptr External pointer to the index.
#' @param k Integer. Number of neighbours, including the point itself.
#' @param ef_search Integer. Beam width at query time.
#' @param sqrt Boolean. Square root the distances (true Euclidean).
#' @param return_dist Boolean. Return the distances.
#' @param verbose Boolean. Print progress.
#'
#' @returns A list with `idx` (1-based integer matrix) and `dist` (double
#' matrix or `NULL`).
#'
#' @keywords internal
rs_hnsw_self <- function(ptr, k, ef_search, sqrt, return_dist, verbose) .Call(wrap__rs_hnsw_self, ptr, k, ef_search, sqrt, return_dist, verbose)

# nolint end
